import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavbarV1 from "@/components/(global)/siteHeader";
import { Footer } from "@/components/(global)/footer";
import { getAllCategories } from "@/actions/categories";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sally Media Ug",
  description: "Generated by custordev",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   const allCategories = (await getAllCategories()) || [];
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="">
          <NavbarV1 allCategories={allCategories}/>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
