import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavbarV1 from "@/components/(global)/siteHeader";
import { Footer } from "@/components/(global)/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sally Media Ug",
  description: "Generated by custordev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="">
          <NavbarV1 />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
