import type { Metadata } from "next";
import { Geist, Azeret_Mono as Geist_Mono } from "next/font/google";
import NavbarV1 from "@/components/(global)/siteHeader";
import { Footer } from "@/components/(global)/footer";
import { getAllCategories } from "@/actions/categories";
import React from "react"; // Import React
// import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sally Media Ug",
  description: "Generated by custordev",
};

export default async function FrontLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const allCategories = (await getAllCategories()) || [];
  return (
    <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

      <NavbarV1 allCategories={allCategories} />

      {children}
      <Footer />
    </div>
  );
}
